"""Browser acceptance for the fictional workbench; requires the local Vite server."""
import os
import re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE_URL = os.environ.get('CARDBOT_PREVIEW_URL', 'http://127.0.0.1:5190')
ARTIFACTS = Path(__file__).resolve().parent / 'artifacts'

def no_overflow(page):
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')

def action(page, value):
    return page.locator(f'[data-wb-action="{value}"]')

def nav(page, value):
    return page.locator(f'.wb-nav[data-view="{value}"]')

def font_px(locator):
    return float(locator.evaluate("el => parseFloat(getComputedStyle(el).fontSize)"))

def skip_to_manifesto(page):
    page.locator('[data-action="skip"]').click()
    expect(page.locator('.login-card')).to_be_visible()
    expect(page.locator('input[type="password"]')).to_be_visible()
    assert page.locator('.login-content').evaluate("el => getComputedStyle(el).opacity") == '1'
    no_overflow(page)
    page.locator('.login-submit').click()
    expect(page.locator('.manifesto')).to_be_visible()
    expect(page.locator('html')).to_have_attribute('lang', 'en')

with sync_playwright() as p:
    ARTIFACTS.mkdir(exist_ok=True)
    browser = p.chromium.launch(headless=True)
    context = browser.new_context(viewport={'width': 1440, 'height': 1000})
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda err: errors.append(str(err)))
    page.goto(BASE_URL + '/?intro=1')
    expect(page.locator('#hello-word')).to_be_visible()
    intro_score = page.get_by_test_id('intro-score')
    expect(intro_score).to_have_attribute('src', re.compile(r'^(?:\./|/)assets/cardbot-intro-score\.m4a$'))
    expect(page.get_by_test_id('intro-audio-toggle').last).to_be_visible()
    assert page.get_by_test_id('intro-audio-toggle').inner_text().strip() == ''
    expect(page.get_by_test_id('intro-audio-toggle').locator('svg')).to_have_count(1)
    initial_mute_state = page.get_by_test_id('intro-audio-toggle').get_attribute('data-muted')
    if initial_mute_state == 'true':
        page.get_by_test_id('intro-audio-toggle').click()
        expect(page.get_by_test_id('intro-audio-toggle')).to_have_attribute('data-muted', 'false')
    else:
        page.get_by_test_id('intro-audio-toggle').click()
        expect(page.get_by_test_id('intro-audio-toggle')).to_have_attribute('data-muted', 'true')
        page.get_by_test_id('intro-audio-toggle').click()
        expect(page.get_by_test_id('intro-audio-toggle')).to_have_attribute('data-muted', 'false')
    page.wait_for_function(
        "document.querySelector('[data-testid=\"intro-score\"]').currentTime > 0.05",
        timeout=3000,
    )
    page.get_by_test_id('intro-audio-toggle').click()
    expect(page.locator('.intro-film')).to_be_visible(timeout=12000)
    expect(page.locator('.intro-film')).to_have_attribute(
        'src', re.compile(r'^(?:\./|/)assets/cardbot-cards-intro\.mp4$')
    )
    expect(page.locator('.intro-film')).to_have_attribute('data-timeline', 'verified', timeout=3000)
    expect(page.locator('.login-card')).to_be_visible(timeout=7000)
    expect(page.locator('.login-card-face')).to_have_count(2)
    assert page.locator('.login-card').evaluate("el => getComputedStyle(el).animationDuration") == '1.8s'
    assert page.locator('.login-card').evaluate("el => getComputedStyle(el).animationName") == 'login-card-turn'
    expect(page.get_by_test_id('intro-audio-toggle').last).to_be_visible()
    expect(page.locator('input[type="password"]')).to_be_visible()
    expect(page.locator('.login-card')).to_have_class(re.compile(r'login-card-rest'), timeout=3000)
    assert intro_score.evaluate('el => el.paused')
    page.locator('.login-submit').click()
    expect(page.locator('.manifesto')).to_be_visible()
    expect(page.locator('html')).to_have_attribute('lang', 'en')
    expect(page.locator('.capabilities span')).to_have_count(5)
    expect(page.locator('.capabilities')).to_contain_text('Evidence')
    assert page.locator('.capabilities span').nth(3).evaluate("el => getComputedStyle(el).color") == 'rgb(109, 74, 255)'
    page.locator('[data-action="workspace"]').last.click()
    expect(page.locator('.wb-company')).to_contain_text('Wangjing Global Trade')
    assert page.locator('.wb-company .wb-avatar').count() == 0
    expect(page.locator('.wb-sidebar')).to_be_visible()
    assert page.locator('.wb-legacy, a[href="/crm.html?intro=0"]').count() == 0
    assert page.locator('.wb-nav[data-view="outbox"] small').count() == 0
    expect(page.get_by_test_id('remote-trigger')).to_be_visible()
    expect(page.get_by_test_id('screensaver-trigger')).to_be_visible()
    assert page.get_by_test_id('screensaver-trigger').inner_text().strip() == ''
    expect(page.get_by_test_id('screensaver-trigger').locator('svg')).to_have_count(1)
    page.get_by_test_id('screensaver-trigger').click()
    expect(page.get_by_test_id('idle-screensaver')).to_be_visible()
    expect(page.get_by_test_id('idle-screensaver')).to_contain_text('YOUR WORLD. IN ONE WORKDAY.')
    expect(page.get_by_test_id('idle-screensaver')).to_contain_text("Let's move")
    assert page.locator('.wb-player').count() == 0
    page.mouse.move(720, 500)
    page.wait_for_timeout(1_200)
    expect(page.get_by_test_id('idle-screensaver')).to_be_visible()
    page.mouse.click(100, 400)
    expect(page.get_by_test_id('idle-screensaver')).to_have_count(0)
    expect(page.locator('#demo-user')).to_be_enabled()
    assert page.locator('.wb-topbar').evaluate("el => getComputedStyle(el).position") == 'sticky'
    assert page.locator('.wb-tour-invite').bounding_box()['height'] < 80
    expect(page.locator('#text-earth')).to_be_visible()
    expect(page.locator('.wb-zone')).to_have_count(6)
    expect(page.locator('#demo-user')).to_have_value('sales-01')
    expect(page.locator('[data-task]')).to_have_count(3)
    expect(nav(page, 'prospecting')).to_be_visible()
    expect(page.locator('.wb-flow-entrances button')).to_have_count(2)
    expect(page.locator('.wb-shared-steps > div')).to_have_count(5)
    overview_panels = page.locator('.wb-overview-grid > .wb-panel')
    expect(overview_panels).to_have_count(2)
    panel_heights = [overview_panels.nth(i).bounding_box()['height'] for i in range(2)]
    assert abs(panel_heights[0] - panel_heights[1]) <= 2
    assert page.locator('.wb-overview-grid .wb-next').evaluate("el => getComputedStyle(el).backgroundColor") == overview_panels.first.evaluate("el => getComputedStyle(el).backgroundColor")
    no_overflow(page)
    page.screenshot(path=str(ARTIFACTS / 'v3-overview-light.png'), full_page=True)
    page.evaluate('scrollTo(0, 600)')
    page.wait_for_timeout(100)
    assert page.locator('.wb-topbar').bounding_box()['y'] <= 1
    assert page.locator('.wb-topbar').evaluate("el => getComputedStyle(el).backgroundColor") == page.locator('.wb-main').evaluate("el => getComputedStyle(el).backgroundColor")
    assert page.locator('.wb-topbar').evaluate("el => getComputedStyle(el).borderBottomLeftRadius") != '0px'
    page.screenshot(path=str(ARTIFACTS / 'v3-sticky-toolbar.png'))
    page.evaluate('scrollTo(0, 0)')
    page.locator('#city').select_option('Europe/London')
    expect(page.locator('html')).to_have_attribute('lang', 'en')
    expect(page.locator('#city')).to_have_value('Europe/London')
    assert page.locator('#shanghai-greeting').inner_text() in {'Good morning', 'Good afternoon', 'Good evening'}
    assert page.locator('.connection-dot').evaluate("el => getComputedStyle(el).backgroundColor") == 'rgb(109, 74, 255)'
    page.locator('.wb-shell').evaluate("el => el.dataset.themeProbe = 'kept'")
    action(page, 'theme').click()
    expect(page.locator('html')).to_have_attribute('data-theme', 'dark')
    expect(page.locator('.wb-shell')).to_have_attribute('data-theme-probe', 'kept')
    page.screenshot(path=str(ARTIFACTS / 'v3-overview-dark-en.png'), full_page=True)
    assert page.locator('.wb-legacy, a[href="/crm.html?intro=0"]').count() == 0
    action(page, 'theme').click()
    action(page, 'language').click()
    expect(page.locator('html')).to_have_attribute('lang', 'zh-CN')
    assert page.locator('html').evaluate("el => el.classList.contains('language-transitioning')")
    page.wait_for_function("!document.documentElement.classList.contains('language-transitioning')")

    # New-customer development is a full qualification path, not an email lookup.
    nav(page, 'prospecting').click()
    expect(page.locator('.wb-prospect-rail button')).to_have_count(6)
    expect(page.locator('.wb-prospect-results')).to_contain_text('Aurora Habitat AB')
    expect(page.locator('.wb-prospect-dossier')).to_contain_text('为什么匹配')
    expect(page.locator('.wb-prospect-action')).to_contain_text('联系方式来源')
    action(page, 'prospect-next').click()
    expect(page.locator('.wb-prospect-process .wb-badge.blue')).to_contain_text('02')
    action(page, 'prospect-next').click()
    action(page, 'prospect-next').click()
    action(page, 'prospect-next').click()
    action(page, 'prospect-finish').click()
    expect(page.locator('.wb-prospect-process .wb-badge.blue')).to_contain_text('06')
    action(page, 'draft-outreach').click()
    expect(page.locator('.wb-draft-switch')).to_contain_text('新客户开发信')
    expect(page.locator('.wb-draft-editor')).to_contain_text('Aurora Habitat')
    action(page, 'approve-outreach').click()
    expect(page.locator('#notice')).to_contain_text('请先核对')
    page.locator('#outreach-review-check').check()
    action(page, 'approve-outreach').click()
    expect(page.locator('#outreach-status')).to_contain_text('已审核')
    action(page, 'save-outreach').click()
    expect(page.locator('.wb-receipt')).to_contain_text('LOCAL-OUTREACH-001')
    expect(page.locator('.wb-receipt')).to_contain_text('审计摘要')

    nav(page, 'workday').click()
    assert page.locator('#text-earth').count() == 0
    page.locator('[data-task="TASK-002"]').click()
    action(page, 'complete').click()
    expect(page.locator('#notice')).to_contain_text('完成依据')
    page.locator('#completion-evidence').fill('MANUAL-REPORT-001')
    action(page, 'complete').click()
    expect(page.locator('[data-task="TASK-002"]')).to_contain_text('已完成')
    action(page, 'evening').click()
    expect(page.locator('.recap')).to_contain_text('报价')
    page.screenshot(path=str(ARTIFACTS / 'v3-workday.png'), full_page=True)

    nav(page, 'evidence').click()
    expect(page.locator('.wb-mail')).to_have_count(2)
    page.locator('[data-mail="EMAIL-000"]').click()
    expect(page.locator('#EMAIL-000')).to_have_class('wb-mail highlight')
    page.screenshot(path=str(ARTIFACTS / 'v3-mail.png'), full_page=True)
    action(page, 'generate').click()
    expect(action(page, 'save-sim')).to_be_disabled()
    action(page, 'approve').click()
    expect(page.locator('#notice')).to_contain_text('勾选')
    page.locator('#review-check').check()
    action(page, 'approve').click()
    body = page.locator('#draft-body').input_value()
    action(page, 'save-fail').click()
    expect(page.locator('#notice')).to_contain_text('内容已保留')
    assert page.locator('#draft-body').input_value() == body
    action(page, 'save-sim').click()
    expect(page.locator('.wb-receipt')).to_contain_text('SIM-OKKI-DRAFT-001')
    expect(page.locator('.wb-receipt')).to_contain_text(body)
    page.screenshot(path=str(ARTIFACTS / 'v3-simulated-outbox.png'), full_page=True)
    page.goto(BASE_URL)
    nav(page, 'outbox').click()
    expect(page.locator('.wb-receipt')).to_contain_text(body)
    nav(page, 'drafts').click()
    page.locator('#draft-body').fill(body + '\nManual revision.')
    expect(action(page, 'save-sim')).to_be_disabled()
    nav(page, 'outbox').click()
    expect(page.locator('.wb-empty')).to_contain_text('还没有')
    before = page.evaluate('localStorage.getItem("cardbot_preview_v1")')

    # Playback advances by itself, pauses, rewinds, and never overwrites manual work.
    action(page, 'tour-start').click()
    expect(page.locator('.wb-player')).to_have_attribute('data-step', '0')
    expect(page.locator('.wb-shell')).to_have_attribute('data-rehearsal-step', '1')
    expect(nav(page, 'prospecting')).to_have_class('wb-nav active tour-live')
    expect(page.locator('.wb-tour-focus')).to_have_count(1)
    expect(page.locator('.wb-tour-focus')).to_have_attribute('data-tour-focus', '1')
    assert page.locator('.player-steps .active').evaluate("el => getComputedStyle(el).backgroundColor") == 'rgb(109, 74, 255)'
    expect(page.locator('.player-steps button')).to_have_count(10)
    expect(page.locator('.wb-player')).to_have_attribute('data-step', '1', timeout=10000)
    expect(page.locator('.wb-shell')).to_have_attribute('data-rehearsal-step', '2')
    expect(nav(page, 'prospecting')).to_have_class('wb-nav active tour-live')
    expect(page.locator('.wb-tour-focus')).to_have_attribute('data-tour-focus', '2')
    action(page, 'tour-play').click()
    page.wait_for_timeout(7500)
    expect(page.locator('.wb-player')).to_have_attribute('data-step', '1')
    action(page, 'tour-next').click()
    expect(page.locator('.wb-prospect-dossier')).to_have_class('wb-panel wb-prospect-dossier wb-tour-focus')
    action(page, 'tour-next').click()
    expect(page.locator('.wb-prospect-action')).to_have_class('wb-panel wb-prospect-action wb-tour-focus')
    action(page, 'tour-next').click()
    expect(page.locator('[data-task]')).to_have_count(3)
    action(page, 'tour-next').click()
    expect(nav(page, 'evidence')).to_have_class('wb-nav active tour-live')
    action(page, 'tour-next').click()
    expect(page.locator('#draft-status')).to_have_text('待人工审核')
    expect(page.locator('#draft-body')).to_have_attribute('readonly', '')
    action(page, 'tour-next').click()
    expect(page.locator('#draft-status')).to_have_text('已审核 · 待保存')
    action(page, 'tour-next').click()
    expect(page.locator('.wb-receipt')).to_contain_text('模拟器')
    page.screenshot(path=str(ARTIFACTS / 'v3-rehearsal-save.png'), full_page=True)
    action(page, 'tour-prev').click()
    expect(page.locator('#draft-status')).to_have_text('已审核 · 待保存')
    page.locator('.player-steps [data-step="9"]').click()
    expect(page.locator('#demo-user')).to_have_value('manager')
    expect(page.locator('.wb-team-task')).to_have_count(3)
    expect(page.locator('.wb-team-task').nth(0)).to_contain_text('待确认')
    expect(page.locator('.wb-team-task').nth(1)).to_contain_text('已完成')
    expect(page.locator('.wb-team-task').nth(2)).to_contain_text('已完成')
    expect(action(page, 'tour-next')).to_be_disabled()
    page.screenshot(path=str(ARTIFACTS / 'v3-rehearsal-team.png'), full_page=True)
    action(page, 'tour-exit').click()
    expect(page.locator('.wb-shell')).not_to_have_class('is-rehearsing')
    expect(page.locator('.wb-tour-focus')).to_have_count(0)
    expect(page.locator('#demo-user')).to_have_value('sales-01')
    assert page.evaluate('localStorage.getItem("cardbot_preview_v1")') == before
    nav(page, 'drafts').click()
    expect(page.locator('#draft-body')).to_have_value(body + '\nManual revision.')

    page.locator('#demo-user').select_option('sales-02')
    expect(page.locator('[data-task]')).to_have_count(0)
    assert nav(page, 'team').count() == 0
    nav(page, 'drafts').click()
    expect(page.locator('.access-boundary')).to_be_visible()
    page.locator('#demo-user').select_option('manager')
    nav(page, 'organization').click()
    expect(page.locator('.wb-identity-row')).to_have_count(4)
    action(page, 'language').click()
    no_overflow(page)
    page.screenshot(path=str(ARTIFACTS / 'v3-organization-en.png'), full_page=True)
    action(page, 'tour-start').click()
    expect(page.locator('#demo-user')).to_be_enabled()
    page.locator('#demo-user').select_option('sales-02')
    expect(page.locator('.wb-player')).to_have_count(0)
    expect(page.locator('#demo-user')).to_have_value('sales-02')
    expect(page.locator('#notice')).to_contain_text('account switched')
    page.wait_for_timeout(20_500)
    expect(page.get_by_test_id('idle-screensaver')).to_be_visible()
    expect(page.get_by_test_id('screensaver-earth')).to_be_visible()
    earth_box = page.get_by_test_id('screensaver-earth').bounding_box()
    assert earth_box['width'] >= 700 and earth_box['height'] >= 700
    earth_frame = page.get_by_test_id('screensaver-earth').evaluate("el => el.toDataURL()")
    page.wait_for_timeout(650)
    assert page.get_by_test_id('screensaver-earth').evaluate("el => el.toDataURL()") != earth_frame
    page.screenshot(path=str(ARTIFACTS / 'v8-idle-screensaver.png'))
    page.keyboard.press('Escape')
    expect(page.get_by_test_id('idle-screensaver')).to_have_count(0)
    assert not errors, errors
    context.close()

    # Personal CardBot: choose a fixed playing-card avatar, save it per demo
    # account, then use the local-only knowledge-assistant conversation demo.
    bot_context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = bot_context.new_page()
    bot_errors = []
    page.on('pageerror', lambda err: bot_errors.append(str(err)))
    page.goto(BASE_URL + '/?intro=1')
    skip_to_manifesto(page)
    page.locator('[data-action="workspace"]').last.click()
    action(page, 'language').click()
    expect(page.locator('html')).to_have_attribute('lang', 'zh-CN')
    expect(page.get_by_test_id('brand-bot')).to_be_visible()
    expect(page.get_by_test_id('brand-bot')).to_have_attribute('data-configured', 'false')
    assert page.get_by_test_id('brand-bot').evaluate("el => getComputedStyle(el).outlineStyle") == 'none'
    page.get_by_test_id('brand-bot').click()
    expect(page.get_by_test_id('bot-picker')).to_be_visible()
    expect(page.locator('.cb-expression')).to_have_count(16)
    expect(page.locator('.cb-color')).to_have_count(12)
    page.locator('[data-bot-action="expression"][data-value="heureux"]').click()
    page.locator('[data-bot-action="color"][data-value="rouge"]').click()
    page.screenshot(path=str(ARTIFACTS / 'v4-bot-picker.png'), full_page=True)
    page.locator('[data-bot-action="picker-save"]').click()
    expect(page.get_by_test_id('bot-chat')).to_be_visible()
    expect(page.get_by_test_id('brand-bot')).to_have_attribute('data-configured', 'true')
    expect(page.get_by_test_id('brand-bot').locator('.cb-bot-face')).to_have_attribute('data-expression', 'heureux')
    expect(page.locator('[data-bot-action="customize"]')).to_have_text('定制')
    expect(page.locator('.cb-chat-suggestions button')).to_have_count(8)
    assert page.locator('.cb-chat-suggestions').evaluate("el => el.scrollWidth > el.clientWidth")
    assert page.locator('.cb-chat-suggestions').evaluate("el => getComputedStyle(el).scrollbarWidth") == 'thin'
    assert page.locator('[data-bot-action="customize"]').evaluate("el => getComputedStyle(el).backgroundColor") == 'rgb(232, 72, 63)'
    assert page.locator('.cb-chat-form .cb-bot-primary').evaluate("el => getComputedStyle(el).backgroundColor") == 'rgb(232, 72, 63)'
    page.locator('[data-bot-action="minimize"]').click()
    default_minimized = page.get_by_test_id('bot-chat-minimized').bounding_box()
    assert 26 <= default_minimized['x'] <= 30
    assert default_minimized['y'] + default_minimized['height'] <= 978
    page.locator('[data-bot-action="expand"]').click()
    expect(page.get_by_test_id('bot-chat')).to_be_visible()
    before_drag = page.get_by_test_id('bot-chat').bounding_box()
    drag_handle = page.locator('[data-bot-drag-handle]')
    handle_box = drag_handle.bounding_box()
    page.mouse.move(handle_box['x'] + 150, handle_box['y'] + 12)
    page.mouse.down()
    page.mouse.move(handle_box['x'] + 430, handle_box['y'] + 90, steps=8)
    page.mouse.up()
    after_drag = page.get_by_test_id('bot-chat').bounding_box()
    assert after_drag['x'] > before_drag['x'] + 150
    page.locator('#bot-question').fill('报价流程怎么走？')
    page.locator('#bot-question').press('Enter')
    expect(page.locator('.cb-chat-messages .user')).to_have_count(1)
    expect(page.locator('.cb-thinking')).to_be_visible()
    expect(page.locator('.cb-chat-messages .assistant')).to_have_count(2)
    expect(page.get_by_test_id('bot-chat')).to_contain_text('报价按四步执行')
    expect(page.get_by_test_id('bot-chat')).not_to_contain_text('演示回答')
    page.locator('[data-bot-action="suggest"][data-prompt="sample"]').click()
    expect(page.locator('.cb-thinking')).to_be_visible()
    expect(page.get_by_test_id('bot-chat')).to_contain_text('常规样品每位客户每次最多 2 件')
    page.screenshot(path=str(ARTIFACTS / 'v4-bot-chat.png'), full_page=True)
    page.locator('[data-bot-action="minimize"]').click()
    expect(page.get_by_test_id('bot-chat-minimized')).to_be_visible()
    minimized_before = page.get_by_test_id('bot-chat-minimized').bounding_box()
    assert minimized_before['width'] <= 178
    assert minimized_before['height'] <= 50
    expect(page.get_by_test_id('bot-chat-minimized').locator('strong')).to_have_text('CardBot')
    assert page.get_by_test_id('bot-chat-minimized').locator('span:not(.cb-bot-face):not(.cb-bot-eyes)').count() == 0
    minimized_drag = page.get_by_test_id('bot-chat-minimized').locator('[data-bot-action="expand"]')
    minimized_drag_box = minimized_drag.bounding_box()
    page.mouse.move(minimized_drag_box['x'] + 12, minimized_drag_box['y'] + 12)
    page.mouse.down()
    page.mouse.move(62, 160, steps=8)
    page.mouse.up()
    minimized_after = page.get_by_test_id('bot-chat-minimized').bounding_box()
    assert minimized_after['x'] < minimized_before['x'] - 100
    assert minimized_after['x'] < 90  # May overlap the left navigation area.
    page.screenshot(path=str(ARTIFACTS / 'v5-bot-minimized-drag.png'), full_page=True)
    page.locator('[data-bot-action="expand"]').click()
    expect(page.get_by_test_id('bot-chat')).to_be_visible()
    action(page, 'language').click()
    action(page, 'theme').click()
    expect(page.get_by_test_id('bot-chat')).to_contain_text('Company knowledge ready')
    expect(page.locator('[data-bot-action="customize"]')).to_have_text('Customize')
    page.screenshot(path=str(ARTIFACTS / 'v4-bot-chat-dark-en.png'), full_page=True)
    page.locator('#demo-user').select_option('sales-02')
    expect(page.get_by_test_id('brand-bot')).to_have_attribute('data-configured', 'false')
    assert page.get_by_test_id('bot-chat').count() == 0
    page.locator('#demo-user').select_option('sales-01')
    expect(page.get_by_test_id('brand-bot')).to_have_attribute('data-configured', 'true')
    expect(page.get_by_test_id('brand-bot').locator('.cb-bot-face')).to_have_attribute('data-expression', 'heureux')
    page.get_by_test_id('remote-trigger').click()
    expect(page.get_by_test_id('remote-dialog')).to_be_visible()
    remote_panels = page.locator('.wb-remote-grid > *')
    expect(remote_panels).to_have_count(2)
    assert all(float(remote_panels.nth(i).evaluate("el => getComputedStyle(el).opacity")) > .98 for i in range(2))
    assert page.get_by_test_id('remote-dialog').bounding_box()['width'] <= 862
    expect(page.get_by_test_id('remote-dialog')).to_contain_text('Connect CardBot')
    expect(page.get_by_test_id('remote-dialog')).to_contain_text('WhatsApp')
    assert page.get_by_test_id('remote-dialog').get_by_text('Telegram', exact=True).count() == 0
    expect(page.locator('.wb-channel-logo svg')).to_have_count(3)
    page.wait_for_timeout(900)
    expect(page.locator('.wb-remote-grid')).to_be_visible()
    assert page.locator('.wb-remote-grid').bounding_box()['height'] > 200
    assert all(float(page.locator('.wb-remote-grid > *').nth(i).evaluate("el => getComputedStyle(el).opacity")) > .98 for i in range(2))
    expect(page.locator('.wb-channel-line')).to_have_count(3)
    channel_line = page.locator('.wb-channel-line').first
    assert abs(channel_line.locator('h4').bounding_box()['y'] - channel_line.locator('p').bounding_box()['y']) < 8
    assert page.locator('.wb-channel-list article').first.bounding_box()['height'] < 115
    page.locator('[data-wb-action="remote-refresh"]').click()
    expect(page.get_by_test_id('remote-dialog')).to_contain_text('QR code refreshed')
    page.screenshot(path=str(ARTIFACTS / 'v4-mobile-remote-dark-en.png'), full_page=True)
    page.locator('[data-wb-action="remote-page-next"]').click()
    expect(page.get_by_test_id('unified-entry-slide')).to_contain_text('Any channel. The same CardBot.')
    expect(page.locator('.wb-channel-bridge .wb-channel-logo svg')).to_have_count(3)
    expect(page.locator('.wb-capability-rail > div')).to_have_count(4)
    assert all(float(page.locator('.wb-capability-rail > div').nth(i).evaluate("el => getComputedStyle(el).opacity")) > .98 for i in range(4))
    page.locator('[data-wb-action="remote-page-next"]').click()
    expect(page.get_by_test_id('prospecting-solution-slide')).to_contain_text('Help sales find prospects worth contacting')
    expect(page.locator('.wb-decision-pipeline article')).to_have_count(4)
    assert all(float(page.locator('.wb-decision-pipeline article').nth(i).evaluate("el => getComputedStyle(el).opacity")) > .98 for i in range(4))
    assert font_px(page.locator('.wb-decision-pipeline small').first) >= 13
    page.keyboard.press('ArrowRight')
    expect(page.get_by_test_id('followup-solution-slide')).to_contain_text('CardBot keeps the work moving')
    expect(page.locator('.wb-plain-flow > div')).to_have_count(5)
    assert font_px(page.locator('.wb-plain-flow small').first) >= 14
    page.keyboard.press('ArrowRight')
    expect(page.get_by_test_id('controlled-ai-slide')).to_contain_text('AI stays on task')
    assert font_px(page.locator('.wb-audit-log small').first) >= 12
    page.keyboard.press('ArrowRight')
    expect(page.get_by_test_id('channel-summary-slide')).to_contain_text('Channels handle quick actions')
    expect(page.get_by_test_id('channel-summary-slide')).to_contain_text('CardBot workbench is the full business system')
    expect(page.locator('.wb-presentation-count')).to_have_text('06 / 06')
    page.screenshot(path=str(ARTIFACTS / 'v6-capability-audit-dark-en.png'), full_page=True)
    page.locator('[data-wb-action="remote-close"]').last.click()
    no_overflow(page)
    assert not bot_errors, bot_errors
    bot_context.close()

    for width in (390, 768, 1920):
        mobile = browser.new_context(viewport={'width': width, 'height': 940}, reduced_motion='reduce')
        page = mobile.new_page()
        page.goto(BASE_URL + '/?intro=1')
        expect(page.locator('#hello-word')).to_have_text('Hello / 你好')
        skip_to_manifesto(page)
        page.locator('[data-action="workspace"]').last.click()
        expect(page.get_by_test_id('screensaver-trigger')).to_be_visible()
        no_overflow(page)
        page.screenshot(path=str(ARTIFACTS / f'v3-overview-{width}.png'), full_page=True)
        if width < 700:
            action(page, 'menu').click()
            expect(page.locator('.wb-sidebar')).to_be_visible()
            page.screenshot(path=str(ARTIFACTS / 'v3-navigation-mobile.png'), full_page=True)
            if width == 390:
                page.get_by_test_id('brand-bot').click()
                expect(page.get_by_test_id('bot-picker')).to_be_visible()
                no_overflow(page)
                page.screenshot(path=str(ARTIFACTS / 'v4-bot-picker-mobile.png'), full_page=True)
                page.locator('[data-bot-action="picker-close"]').click()
                page.get_by_test_id('remote-trigger').click()
                expect(page.get_by_test_id('remote-dialog')).to_be_visible()
                no_overflow(page)
                page.screenshot(path=str(ARTIFACTS / 'v4-mobile-remote-390.png'), full_page=True)
                page.locator('[data-wb-action="remote-page-next"]').click()
                expect(page.get_by_test_id('unified-entry-slide')).to_be_visible()
                no_overflow(page)
                page.screenshot(path=str(ARTIFACTS / 'v6-capability-overview-390.png'), full_page=True)
                page.locator('[data-wb-action="remote-close"]').last.click()
                nav(page, 'prospecting').click()
                expect(page.locator('.wb-prospect-rail button')).to_have_count(6)
                no_overflow(page)
                page.screenshot(path=str(ARTIFACTS / 'v7-prospecting-390.png'), full_page=True)
                action(page, 'menu').click()
        nav(page, 'evidence').click()
        no_overflow(page)
        action(page, 'tour-start').click()
        action(page, 'tour-play').click()
        page.locator('.player-steps [data-step="4"]').click()
        no_overflow(page)
        page.screenshot(path=str(ARTIFACTS / f'v3-rehearsal-{width}.png'), full_page=True)
        mobile.close()
    browser.close()
print('PASS: 20-second rotating-globe screensaver and compact screensaver preview trigger, new MP4 entry timeline, 108-frame login turn, sequential rehearsal focus, workbench, personal CardBot picker/chat/drag/accent, mobile remote and capability presentation, bilingual themes, evidence, review gates, simulated save/failure, persistence, rehearsal playback/pause/rewind/isolation, roles and responsive layouts')
