import assert from "node:assert/strict";
import { freshPreview, createDraft, editDraft, approveDraft, saveDraft, completeTask } from "./preview-store";
const state = freshPreview();
const ids = state.tasks.map(t => t.id);
assert.throws(() => saveDraft(state));
assert.throws(() => approveDraft(state));
assert.throws(() => completeTask(state, "TASK-002", ""));
createDraft(state);
assert.equal(state.draft.status, "awaiting_review");
assert.throws(() => saveDraft(state));
approveDraft(state); saveDraft(state);
assert.equal(state.draft.status, "saved_local");
assert.equal(state.tasks[0].status, "needs_confirmation");
editDraft(state, "New text");
assert.equal(state.draft.status, "awaiting_review");
assert.equal(state.draft.savedAt, undefined);
assert.throws(() => saveDraft(state));
completeTask(state, "TASK-002", "Report reference 001");
state.phase = "evening";
assert.deepEqual(state.tasks.map(t => t.id), ids);
assert.equal(state.tasks[1].status, "done");
assert.equal(state.tasks[1].evidence, "Report reference 001");
console.log("PASS: 13 preview domain assertions");
